# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20161228_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to=event.models.get_file_path, verbose_name='活动海报'),
        ),
    ]
