# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20161228_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='日期')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('subject', models.CharField(max_length=60, verbose_name='主题')),
                ('place', models.CharField(max_length=100, verbose_name='地点')),
                ('sort', models.SmallIntegerField(default=1, verbose_name='排序')),
                ('intro', models.TextField(verbose_name='简介')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
            ],
        ),
    ]
