# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='end_time',
            field=models.TimeField(verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='start_time',
            field=models.TimeField(verbose_name='开始时间'),
        ),
    ]
