# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.IntegerField()),
                ('username', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('nickname', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=1)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('active_key', models.CharField(max_length=128)),
                ('active_key_exp', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('last_login_time', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
