# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0002_auto_20161201_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=254)),
                ('website', models.URLField()),
                ('remark', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='RbacRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('remark', models.CharField(max_length=254)),
                ('status', models.SmallIntegerField(default=1)),
                ('rules', models.CharField(max_length=600, validators=['validate_comma_separated_integer_list'])),
            ],
        ),
        migrations.CreateModel(
            name='RbacRoleAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('role_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RbacRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(default=0)),
                ('xlevel', models.SmallIntegerField(default=0)),
                ('name', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=80)),
                ('status', models.SmallIntegerField(default=1)),
                ('condition', models.CharField(max_length=100)),
                ('is_menu', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
