# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0003_auto_20161204_1023'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rbacrole',
            table='auth_rbac_role',
        ),
        migrations.AlterModelTable(
            name='rbacroleaccess',
            table='auth_rbac_role_access',
        ),
        migrations.AlterModelTable(
            name='rbacrule',
            table='auth_rbac_rule',
        ),
    ]
