# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0004_auto_20161204_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='address',
            field=models.CharField(max_length=254, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='电子邮件'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='机构名称'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='pid',
            field=models.IntegerField(default=0, verbose_name='父节点'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='remark',
            field=models.TextField(verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='website',
            field=models.URLField(verbose_name='网址'),
        ),
        migrations.AlterField(
            model_name='rbacrule',
            name='condition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='附加条件'),
        ),
        migrations.AlterField(
            model_name='rbacrule',
            name='is_menu',
            field=models.BooleanField(default=False, verbose_name='是否作为菜单'),
        ),
        migrations.AlterField(
            model_name='rbacrule',
            name='name',
            field=models.CharField(max_length=80, verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='rbacrule',
            name='pid',
            field=models.IntegerField(default=0, verbose_name='上级权限'),
        ),
        migrations.AlterField(
            model_name='rbacrule',
            name='title',
            field=models.CharField(max_length=80, verbose_name='权限名称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='agency_id',
            field=models.IntegerField(default=1, verbose_name='所属机构'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=30, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.SmallIntegerField(default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(max_length=254, unique=True, verbose_name='用户名'),
        ),
    ]
