# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0005_auto_20161217_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rbacroleaccess',
            name='role_id',
        ),
        migrations.AddField(
            model_name='rbacroleaccess',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.RbacRole'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rbacrole',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='角色名称'),
        ),
        migrations.AlterField(
            model_name='rbacrole',
            name='remark',
            field=models.CharField(max_length=254, verbose_name='描述'),
        ),
    ]
