# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0006_auto_20161226_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_key',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='active_key_exp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_time',
            field=models.DateTimeField(null=True),
        ),
    ]
